### ISSUE TITLE
How is sticky-position finding out native support?

### ISSUE THREAD

**Issue by juhaelee** [jackmoore/sticky-position#2]
``` javascript
const nativeSupport = (function(){      
        if (this.isSupported !== null) {
            return this.isSupported;
        } else {
            const style = document.createElement('test').style;
            style.cssText = ['-webkit-', '-ms-', ''].map(prefix => `position: ${prefix}sticky`).join(';');
            this.isSupported = style.position.indexOf('sticky') !== -1;
            return this.isSupported;
        }
    }).bind({isSupported: null});
```

Wouldn't `isSupported` always be null, so wouldn't the else clause always be executed?

@jackmoore

**Comment by jackmoore** [comment]
The first time the function is called, the else clause will execute and set `this.isSupported` to be either `true` or `false`. Know that `bind` is being invoked just once in the creation of the function, and each call to the function references the same object that was passed to bind, so value of `this.isSupported` is persistent between calls.
